### ISSUE TITLE
Home page bottom portion

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-tiffany-ranish/geekwise-wordpress#9]
*the "fast no fluff" line needs to be bold in the other font and smaller
*the links under the icons also need to be bold
*the 3 columns need to be spaced further apart

their site:
![screen shot 2016-05-20 at 8 59 23 am](https://cloud.githubusercontent.com/assets/7436666/15434207/acf2d632-1e6a-11e6-8a01-9e0e4344a308.png)

your site:
![screen shot 2016-05-20 at 9 07 37 am](https://cloud.githubusercontent.com/assets/7436666/15434216/b4e3c11c-1e6a-11e6-92af-8ec5e272ad14.png)

**Comment by geekwise-tiffany-ranish** [comment]
@Sramos9191 please review
